name = "steam-profile-api"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

compatibility_date = "2025-10-18"

# Cloudflare KV 命名空间绑定（可选缓存）
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"

# 环境变量（在 wrangler.toml 中或通过 CLI 设置）
[env.production]
vars = { STEAM_API_KEY = "your-key", STEAM_USER_ID = "your-id" }

[env.development]
vars = { LOG_LEVEL = "debug" }

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts", "lib/**/*.ts"]

[assets]
directory = "./dist"
